config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#index"
  get "/about", to: "pages#about"
  get "/pricing", to: "pages#pricing"
  get "/payment", to: "pages#payment"
  post "/checkout", to: "pages#checkout"

  resources :mailboxes do
    collection do
      get :draft
      get :sent
    end

    member do
      post :send
    end
  end

  resources :boards do
    resources :posts, shallow: true do
      resources :comments, shallow: true, only: [:create]
    end

    member do
      post :favorite
      put :hide
    end

  end

  # resources :favorites, except: [:show, :edit] #不需要就不要開
    resources :favorites, only: [:index]

  resources :users, only: [:create] do #想要有自己的網址，就可以把:new刪掉，自己在下面建立
    collection do
      get :sign_up
      get :edit
      patch :update
      get :sign_in
      post :login
      delete :sign_out #也可以用get, 但可以想成是刪除session
    end
  end

  namespace :api do
    namespace :v1 do
      resources :boards, only: [:index]
    end
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

end

app/views/shared/frontend/_footer.html.erb
    <div class="text-center small text-color-grey">
      © 2020, PPT.com All Rights Reserved.
    </div>

app/views/shared/frontend/_navbar.html.erb
<nav class="position-relative">
  <h1 class="col top-banner text-color-yellow bgc-blue text-center">
    <%= link_to "批批踢實業坊", root_path %>
  </h1>
  <ul class="login position-absolute mr-2 d-flex justify-content-end text-color-white">
    <% if user_signed_in? %>
    <li class="mr-3">Hi~ <%= current_user.account %></li> 
    <li><%= link_to "登出", sign_out_users_path, method: 'delete' %></li>
    <% else %>
    <li class="mr-3"><%= link_to "登入", sign_in_users_path %></li>
    <li><%= link_to "註冊", sign_up_users_path %></li>
    <% end %>
  </ul>
</nav>   