config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#index"
  get "/about", to: "pages#about"
  get "/pricing", to: "pages#pricing"
  get "/payment", to: "pages#payment"
  post "/checkout", to: "pages#checkout"

  resources :mailboxes do
    collection do
      get :draft
      get :sent
    end

    member do
      post :send
    end
  end

  resources :boards do
    resources :posts, shallow: true do
      resources :comments, shallow: true, only: [:create]
    end

    member do
      post :favorite
      put :hide
    end

  end

  # resources :favorites, except: [:show, :edit] #不需要就不要開
    resources :favorites, only: [:index]

  resources :users, only: [:create] do #想要有自己的網址，就可以把:new刪掉，自己在下面建立
    collection do
      get :sign_up
      get :edit
      patch :update
      get :sign_in
      post :login
      delete :sign_out #也可以用get, 但可以想成是刪除session
    end
  end

  namespace :api do
    namespace :v1 do
      resources :boards, only: [:index]
    end
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

end

app/views/pages/about.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  hi
</body>
</html>

app/views/pages/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <div id="app">
        <App></App>
      </div>
      <div class="main-banner">
      </div>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="">
      <ul class="p-0 mx-3 text-left text-color-grey">
        <li>(A)nnounce</li>
        <li><%= link_to "(F)avorite", favorites_path %></li>
        <li><%= link_to "(C)lass", boards_path %></li>
        <li>(M)ail</li>
        <li>(T)alk</li>
        <li>(U)ser</li>
        <li>(X)yz</li>
        <li>(P)lay</li>
        <li>(N)amelist</li>
        <li>(G)oodbye</li>
      </ul>
    </div>
    <div class="">
      <ul class="p-0 mx-3 text-center text-color-grey">
        <li>【精華公佈欄】</li>
        <li><%= link_to "【 我 的 最愛 】", favorites_path %></li>
        <li><%= link_to "【分組討論區】", boards_path %></li>
        <li>【私人信件區】</li>
        <li>【休閒聊天區】</li>
        <li>【個人設定區】</li>
        <li>【系統資訊區】</li>
        <li>【娛樂與休閒】</li>
        <li>【編特別名單】</li>
        <li>  離開，再見...</li>
      </ul>
    </div>
  </div>
</div>

app/views/pages/payment.html.erb
<head>
  <meta charset="utf-8">
  <script src="https://js.braintreegateway.com/web/dropin/1.23.0/js/dropin.min.js"></script>
</head>
<body>
  <h1>方案 <%= @plan.upcase %></h1>
  <h2>價錢 <%= @price %></h2>

<%= form_with(url: "/checkout?plan=#{@plan}", id: 'payment_form', method: 'post', local: true) do %>
  <div id="dropin-container"></div>
  <button id="submit-button">付款</button>
  <input type="hidden" value="" id="nonce" name="nonce">
<% end %>

  <script>
    var button = document.querySelector('#submit-button');

    braintree.dropin.create({
      authorization: '<%= @token %>',
      container: '#dropin-container'
    }, function (createErr, instance) {
      button.addEventListener('click', function (e) {
        e.preventDefault(); //把原本button的行為停下來，改為以下自己寫的順序與方式
        
        instance.requestPaymentMethod(function (err, payload) {
          //console.log(payload.nonce) //取得nonce
          const nonce_dom = document.querySelector('#nonce');
          const form = document.querySelector('#payment_form');
          nonce_dom.value = payload.nonce; //把token塞改form
          form.submit(); //官網第四步，method和url回該form_with設定
        });
      });
    });
  </script>
</body>

app/views/pages/pricing.html.erb
<h1>方案說明</h1>
<table class="pricing_table my-5">
  <thead>
    <tr>
      <td>免費會員</td>
      <td>Plan A</td>
      <td>Plan B</td>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><ul>
      Features:
        <li>不可新增看板</li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
      </ul></td>
      <td><ul>
      Features:
        <li>可新增2個看板</li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
      </ul></td>
      <td><ul>
      Features:
        <li>可新增無限看板</li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
      </ul></td>
    </tr>
    <tr>
      <td>終身免費</td>
      <td><%= ENV["plan_a_price"] %>元</td>
      <td><%= ENV["plan_b_price"] %>元</td>
    </tr>
    <tr>
      <td></td>
      <td><%= link_to "去結帳", payment_path(plan: 'a') %></td>
      <td><%= link_to "去結帳", payment_path(plan: 'b') %></td>
    </tr>
  </tbody>
</table>