config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#index"
  get "/about", to: "pages#about"
  get "/pricing", to: "pages#pricing"
  get "/payment", to: "pages#payment"
  post "/checkout", to: "pages#checkout"

  resources :mailboxes do
    collection do
      get :draft
      get :sent
    end

    member do
      post :send
    end
  end

  resources :boards do
    resources :posts, shallow: true do
      resources :comments, shallow: true, only: [:create]
    end

    member do
      post :favorite
      put :hide
    end

  end

  # resources :favorites, except: [:show, :edit] #不需要就不要開
    resources :favorites, only: [:index]

  resources :users, only: [:create] do #想要有自己的網址，就可以把:new刪掉，自己在下面建立
    collection do
      get :sign_up
      get :edit
      patch :update
      get :sign_in
      post :login
      delete :sign_out #也可以用get, 但可以想成是刪除session
    end
  end

  namespace :api do
    namespace :v1 do
      resources :boards, only: [:index]
    end
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

end

app/models/board.rb
class Board < ApplicationRecord
  acts_as_paranoid
  
  validates :title, presence: true, length: { minimum: 2 }

  has_many :posts
  has_many :board_masters
  has_many :users, through: :board_masters

  has_many :favorite_boards
  has_many :favorited_users, through: :favorite_boards, source: :user

  default_scope { where(deleted_at: nil) }

  def destroy #也可以做一個軟刪除模組，掛在有需要的Model身上
    update(deleted_at: Time.now)
  end

  def favorited_by?(u)
    favorited_users.include?(u)
  end

  include AASM

  aasm(column: 'state') do
    state :normal, initial: true
    state :hidden, :locked

    event :hide do
      transitions from: [:normal, :locked], to: :hidden
    end

    event :show do
      transitions from: :hidden, to: :locked
    end

    event :lock do
      transitions from: [:normal, :hidden], to: :locked

      after_transaction do
        puts "已鎖板！"
      end
    end

    event :unlock do
      transitions from: :locked, to: :normal
    end
  end

end

app/controllers/api/v1/boards_controller.rb
class Api::V1::BoardsController < ApplicationController
  def index
    @boards = Board.all
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  # app/views/layouts/boards.html.erb
  # 若找不到則往上
  # app/views/layouts/application.html.erb
  before_action :find_board, only: [:favorite, :show, :edit, :update, :destroy, :hide]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @boards = Board.normal.page(params[:page]).per(8)
  end

  def show
    @post = @board.posts.includes(:user)
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML,
    filter_html: true,
    autolink: true,
    tables: true)
    @intro = markdown.render(@board.intro)
  end

  def favorite
    current_user.toggle_favorite_board(@board)

    respond_to do |format|
      format.html { redirect_to board_path, notice: 'OK!' }
      format.json { render json: { status: @board.favorited_by?(current_user) }} #此方法寫在board model上
    # else  
    #   format.html {}
    #   format.json {}
    end

    # redirect_to board_path
    # redirect_to favorites_path, notice: 'OK!'
  end

  def new
    if user_signed_in?
      @board = Board.new #因為new有帶入預設值，所以變數不夠也沒關係
    else
      redirect_to root_path, notice: "請先登入會員"
    end
  
    authorize @board, :new?
  end

  def create
    @board = Board.new(board_params)
    @board.users << current_user
    authorize @board, :create?
    if @board.save
      redirect_to boards_path, notice: "新增成功"
    else
      render :new, alert: "新增失敗" #會重新產生new頁面，且會有board_params的參數帶入原本的form (form_for的設計)
    end

    # Board.create(title: params[:title], intro: params[:intro])
    # render html: "ok"
  end

  def edit
  end

  def update
    if @board.update(board_params)
      redirect_to boards_path, notice: "更新成功"
    else
      render :edit, alert: "更新失敗" #會重新產生new頁面，且會有board_params的參數帶入原本的form (form_for的設計)
    end
  end

  def destroy
    @board.destroy
    redirect_to boards_path, notice: "刪除成功"
  end
  
  def hide
    @board.hide! if @board.may_hide?
    redirect_to boards_path, notice: "隱板成功"
  end

  private
  def find_board
    @board = Board.find(params[:id])
  end

  def board_params
    params.require(:board).permit(:title, :intro) #沒有寫的就會被濾掉
  end

end

app/helpers/api/v1/boards_helper.rb
module Api::V1::BoardsHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
  def display_bm(board)
    if board.users.count == 0
      "徵求中"
    else
      board.users.map { |user| user.account }.join(" / ")
    end
  end
end

app/views/boards/_form.html.erb
<% if board.errors.any?  %>
  <ul>
  <% board.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
<% end %>

<%= form_for(board) do |f| %>
  <div class="fields">
    <%= f.label :title, "看板名稱" %>
    <%= f.text_field :title %>
  </div>

  <div class="fields">
    <%= f.label :intro, "看板說明" %>
    <%= f.text_area :intro %>
  </div>
  
  <%= f.submit "送出" %>
<% end %>

app/views/boards/edit.html.erb
<h1>編輯看板</h1>
<%= render 'form', board: @board %>

app/views/boards/index.html.erb
<div class="container">
  <h1 class="text-center">所有看板</h1>
  <% if policy(:board).create? %>
  <span><%= link_to "新增看板", new_board_path %></span>
  <% end %>
  <div id="board" class="row">
    <%# <Board></Board> %>
  </div>

  <div class="row">
    <% @boards.each do |board| %>
      <div class="col-12 col-md-6 col-lg-3 mb-4">
        <div class="card h-100">
          <div class="card-body d-flex flex-column justify-content-between">
            <%= link_to board_path(board) do %> 
              <div class="words">
                <h2 class="card-title h4">
                  <%= board.title %> 
                </h2>
                <p class="card-text">
                  <%# <%= board.intro %> 
                </p>
              </div>
            <% end %>
            <div class="links pt-4">
              <%= link_to edit_board_path(board) do %> 
                <i class="fa fa-pen btn btn-light btn-sm"></i>
              <% end %>
              <%= link_to board_path(board), method: 'delete', data: { confirm: '確定刪除？' } do %> 
                <i class="fa fa-trash btn btn-light btn-sm"></i>
              <% end %>
              <%= link_to hide_board_path(board), method: 'put', data: { confirm: '確定隱板？' } do %>
                <i class="fas fa-eye-slash btn btn-light btn-sm"></i>
              <% end %>
            </div>
          </div>
        </div> 
      </div>
    <% end %>
  </div>
  <%= paginate @boards %>
</div>

app/views/boards/new.html.erb
<h1>新增看板</h1>
<%= render 'form', board: @board %>

app/views/boards/show.html.erb
<span><%= link_to "返回全部看板", boards_path %></span>
<h1 data-controller="heart" data-heart-board-id="<%= @board.id %>">
  看板 <%= @board.title %><%= @intro.html_safe %>
    <span class="text-color-white" data-action="click->heart#favorite">
      <% if current_user.favorited_boards.exists? %>
        <i class="fas fa-heart small" data-target="heart.heart"></i>
       <% else %>
         <i class="far fa-heart small"></i>
       <% end %> 
    </span>
</h1>
<%= @intro.html_safe %>
<div class="bm">
  <span>[版主：<%= display_bm(@board) %>]</span>
</div>
  <span><%= link_to "新增文章", new_board_post_path(@board) %></span>
  <ul>
  <% @board.posts.each do |post| %>
    <li data-controller="post" data-action="heypost@window->post#callpost">
      <% if post.deleted_at == nil %>
      <%= post.display_user_name %>  <%# 作用在post, 所以把display_user_name這個method寫在post %>
      <% end %>
      <%= link_to post.title, post, data: { target: 'post.title' } %>
      <% if policy(:post).edit?(post) %>
        <%= link_to "編輯",  edit_post_path(post) %>
      <% end %>
      <% if policy(:post).destroy?(post) %>
        <%= link_to "刪除", post_path(post), method: 'delete', data: { confirm: '確定刪除？' } %>
      <% end %>
    </li>
  <% end %>
</ul>