config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#index"
  get "/about", to: "pages#about"
  get "/pricing", to: "pages#pricing"
  get "/payment", to: "pages#payment"
  post "/checkout", to: "pages#checkout"

  resources :mailboxes do
    collection do
      get :draft
      get :sent
    end

    member do
      post :send
    end
  end

  resources :boards do
    resources :posts, shallow: true do
      resources :comments, shallow: true, only: [:create]
    end

    member do
      post :favorite
      put :hide
    end

  end

  # resources :favorites, except: [:show, :edit] #不需要就不要開
    resources :favorites, only: [:index]

  resources :users, only: [:create] do #想要有自己的網址，就可以把:new刪掉，自己在下面建立
    collection do
      get :sign_up
      get :edit
      patch :update
      get :sign_in
      post :login
      delete :sign_out #也可以用get, 但可以想成是刪除session
    end
  end

  namespace :api do
    namespace :v1 do
      resources :boards, only: [:index]
    end
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_paranoid
  has_rich_text :hello

  validates :title, presence: true
  validates :serial, uniqueness: true

  belongs_to :board
  belongs_to :user
  has_many :comments
  has_one_attached :photo

  before_create :create_serial #before_validation -> 須確認是否是新資料

  def display_user_name
    user.nil? ? "-" : user.account
  end

  private
  def create_serial
    puts "-----"
    self.serial = serial_generator(10)
  end

  def serial_generator(n)
    [*'a'..'z', *'A'..'Z', *0..9].sample(n).join
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_board, only: [:new, :create]
  before_action :find_post, only: [:show, :destroy]
  before_action :find_board_by_post, only: [:show, :destroy]
  before_action :authenticate_user!, except: [:index, :show]


  def index
    @posts = Post.all
  end
  
  def new
    @post = @board.posts.new
  end

  def create
    @post = @board.posts.new(post_params)

    if @post.save
      # UserMailer.with(user: @user).welcome_email.deliver_later
      SendmailJob.perform_later(@post)
      redirect_to @board, notice: '文章新增成功'
    else
      render :new, alert: "文章新增失敗" #會重新產生new頁面，且會有board_params的參數帶入原本的form (form_for的設計)
    end
  end

  def edit
    # @post = Post.find_by(id: params[:id], user: current_user) 
    @post = current_user.posts.find(params[:id])
    @board = Board.find(@post.board_id)
  end

  def update
    @post = current_user.posts.find(params[:id])
    @board = Board.find(@post.board_id)
    if @post.update(post_params)
      redirect_to @post, notice: '文章更新成功'
    else
      render :edit, alert: "文章更新失敗" #會重新產生edit頁面，且會有board_params的參數帶入原本的form (form_for的設計)
    end
  end

  def destroy
    if policy(:post).destroy?(@post)
      @post.destroy
      redirect_to board_path(@board), notice: "刪除成功"
    else
      redirect_to board_path(@board), notice: "您沒有權限"
    end
  end

  def show
    @comment = @post.comments.new
    @comments = @post.comments.all.order(id: :desc)
  end
  
  private
  def find_post
    @post = Post.find(params[:id])
  end

  def find_board
    @board = Board.find(params[:board_id])
  end

  def find_board_by_post
    # @board = Board.find_by(id: @post.board_id)
    @board = Board.find(@post.board_id)
  end

  def post_params
    params.require(:post)
          .permit(:title, :content, :photo, :hello)
          .merge(user: current_user) #belongs_to 產生的user，此處只是產生一個hash欄位而已
          #有或沒有!都沒差, 因為此處只要回傳結果
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col text-center">
      <% if post.errors.any?  %>
        <ul>
        <% post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      <% end %>
      
      <%= form_with(model: post, url: board_posts_path, local: true) do |form| %>
        <div class="fields text-color-grey">
          <%= form.label :title, "文章名稱" %>
          <%= form.text_field :title %>
        </div>
      
        <div class="fields text-color-grey">
          <%= form.label :content, "文章內容" %>
          <%= form.text_area :content %>
        </div>

        <div class="fields text-color-grey">
          <%= form.label :hello, "內文" %>
          <div class="rich-text-field text-color-black text-left">
            <%= form.rich_text_area :hello %>
          </div>
        </div>

        <div class="fields text-color-grey">
          <%= form.label :photo, "附件" %>
          <%= form.file_field :photo %>
        </div>
        
        <%= form.submit "發文" %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<span><%= link_to "取消", board_path(@board) %></span>
<h1>編輯文章</h1>
<% post = @post %>
<% if post.errors.any?  %>
  <ul>
  <% post.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
<% end %>

<%= form_with(model: post, url: post_path) do |form| %>
  <div class="fields">
    <%= form.label :title, "文章名稱" %>
    <%= form.text_field :title %>
  </div>

  <div class="fields">
    <%= form.label :content, "文章內容" %>
    <%= form.text_area :content %>
  </div>
  
  <%= form.submit "存擋" %>
<% end %>

app/views/posts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col text-center">
      <span><%= link_to "取消", board_path(@board) %></span>
      <h1>新增文章</h1>
      <%= render 'form', post: @post %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="row justify-content-between">
    <div class="post-header-left d-flex">
      <ul class="px-2">
        <li>作者</li>
        <li>標題</li>
        <li>時間</li>
      </ul>
      <ul class="px-2">
        <li><%= @post.display_user_name %></li>
        <li class="post-title"><%= @post.title %></li>
        <li><%= @post.created_at %></li>
      </ul>
    </div>
    <div class="post-header-right d-flex">
      <ul class="px-2">
        <li>看板</li>
      </ul>
      <ul class="px-2">
        <li><%= @board.title %></li>
      </ul>
    </div>
  </div>
  <div class="row">
    <p class="post-content">
      <%= @post.content %>
      <%= @post.hello %>
      <%= image_tag @post.photo.variant(resize_to_limit: [400, 400]) if @post.photo.attached? %>    </p>
  </div>
  <div class="row">
    <ul class="px-2">
      <li>
        <span><%= link_to "回到看板" + @board.title, board_path(@board) %></span>
      </li>
      <li>
        <% if policy(:post).edit?(@post) %>
          <%= link_to "編輯",  edit_post_path(@post) %>
        <% end %>
      </li>
      <li>
        <% if policy(:post).destroy?(@post) %>
          <%= link_to "刪除", post_path(@post), method: 'delete', data: { confirm: '確定刪除？' } %>
        <% end %>
      </li>
    </ul>
  </div>
  <div class="row">
    <div class="col px-2">
      <%= form_with(model: @comment, url: post_comments_path(@post)) do |form| %>
      <%= form.text_field :content %>
      <%= form.submit "送出" %>
      <% end %>
    </div>
  </div>
  <% @comments.each do |comment| %>
    <div class="row">
      <div class="post-comment col-2 px-2 d-flex justify-content-between">
        <div class="post-comments-account text-color-yellow">
          <%= comment.user.account %>
        </div>
        <span class="text-color-yellow">：</span>
      </div>
      <div class="text-color-grey col-5 px-2">
        <%= comment.content %>
      </div>
      <div class="text-color-grey col-2 px-2">
        <%= comment.ip_address %>
      </div>
      <div class="text-color-grey col-3 px-2 text-right">
        <%= comment.created_at.in_time_zone("Taipei").strftime('%m/%d %H:%M') %>
      </div>
    </div>
  <% end %>
</div>